### ISSUE TITLE
Missing resource.h

### ISSUE THREAD

**Issue by teejaydub** [branch-predictor/BPSpeller#1]
Thanks for sharing this!

I tried compiling it in Visual Studio 17.3 (Community Edition 2022) and I end up with "cannot open include file 'resource.h'."

Did that file just get omitted from the Git repo?

**Comment by branch-predictor** [comment]
Actually, yes. Thanks for spotting this - just pushed the missing file.

**Comment by teejaydub** [comment]
So quick, thanks!
